version: '3'
services:
  jupyternotebook:
    image: poc/notebook
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/work
      - ~/.aws:/home/jovyan/.aws
    environment:
      - MLFLOW_TRACKING_URI=http://production.yg2upmxaxt.us-east-1.elasticbeanstalk.com
      - JUPYTER_ENABLE_LAB=yes
      - USER
    working_dir: /home/jovyan/work