version: '3'
services:
  jupyternotebook:
    image: poc/notebook
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/work
      - ~/.aws:/home/jovyan/.aws
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - USER